### ISSUE TITLE
✅ Change Colors and background hover of the options 👏

### ISSUE THREAD

**Issue by mjesusoj** [mjesusoj/Course-Vue#1]
### **TODOS**

- [x] Colors headers and other ✅

- [x] Color Button and Options 🎉

- [x] Options background hover 🚀

- [x] Add more height to Button "New Game" 🎉

**Comment by mjesusoj** [comment]
Finish and close this issue 🚀💪
